name: manage-azure-policy-737f8b4f
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Restrict_location_of_information_processing,_storage_and_services_0040d2e5-2779-170d-6a2c-1f5fca353335/**'
#      - 'policies/Vulnerability_assessment_should_be_enabled_on_your_Synapse_workspaces_0049a6b3-a662-4f3e-8635-39cf44ace45a/**'
#      - 'policies/SQL_Server_Integration_Services_integration_runtimes_on_Azure_Data_Factory_should_be_joined_to_a_virtual_network_0088bc63-6dee-4a9c-9d29-91cfdc848952/**'
#      - 'policies/Establish_parameters_for_searching_secret_authenticators_and_verifiers_0065241c-72e9-3b2c-556f-75de66332a94/**'
#      - 'policies/_Preview_Configure_VMSS_created_with_Shared_Image_Gallery_images_to_install_the_Guest_Attestation_extension_009259b0-12e8-42c9-94e7-7af86aa58d13/**'
#      - 'policies/Private_endpoint_connections_on_Batch_accounts_should_be_enabled_009a0c92-f5b4-4776-9b66-4ed2b4775563/**'
#      - 'policies/Integrate_risk_management_process_into_SDLC_00f12b6f-10d7-8117-9577-0f2b76488385/**'
#      - 'policies/View_and_configure_system_diagnostic_data_0123edae-3567-a05a-9b05-b53ebe9d3e7e/**'
#      - 'policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**'
#      - 'policies/Enforce_resource_locks_on_resource_groups_lll/**'
#      - 'policies/Enforce_resource_locks_on_resource_groups_WIN_locks/**'
#      - 'policies/Change_Storage_Minimum_Tls_Version_storage_tls/**'
#      - 'policies/Enforce_resource_locks_on_resource_groups_test/**'
#      - 'policies/Require_a_tag_on_subscription_CUSTOM_Tag_name_required_-_testname/**'
#      - 'policies/Restrict_allowed_locations_for_resources_restrict-allowed-locations-policy-test/**'
#      - 'policies/Append_test_1001_6f85b2e4-9a7c-4758-a14a-8e243e3abbed/**'
#      - .github/workflows/manage-azure-policy-737f8b4f.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_737f8b4f}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Restrict_location_of_information_processing,_storage_and_services_0040d2e5-2779-170d-6a2c-1f5fca353335/**
          policies/Vulnerability_assessment_should_be_enabled_on_your_Synapse_workspaces_0049a6b3-a662-4f3e-8635-39cf44ace45a/**
          policies/SQL_Server_Integration_Services_integration_runtimes_on_Azure_Data_Factory_should_be_joined_to_a_virtual_network_0088bc63-6dee-4a9c-9d29-91cfdc848952/**
          policies/Establish_parameters_for_searching_secret_authenticators_and_verifiers_0065241c-72e9-3b2c-556f-75de66332a94/**
          policies/_Preview_Configure_VMSS_created_with_Shared_Image_Gallery_images_to_install_the_Guest_Attestation_extension_009259b0-12e8-42c9-94e7-7af86aa58d13/**
          policies/Private_endpoint_connections_on_Batch_accounts_should_be_enabled_009a0c92-f5b4-4776-9b66-4ed2b4775563/**
          policies/Integrate_risk_management_process_into_SDLC_00f12b6f-10d7-8117-9577-0f2b76488385/**
          policies/View_and_configure_system_diagnostic_data_0123edae-3567-a05a-9b05-b53ebe9d3e7e/**
          policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**
          policies/Enforce_resource_locks_on_resource_groups_lll/**
          policies/Enforce_resource_locks_on_resource_groups_WIN_locks/**
          policies/Change_Storage_Minimum_Tls_Version_storage_tls/**
          policies/Enforce_resource_locks_on_resource_groups_test/**
          policies/Require_a_tag_on_subscription_CUSTOM_Tag_name_required_-_testname/**
          policies/Restrict_allowed_locations_for_resources_restrict-allowed-locations-policy-test/**
          policies/Append_test_1001_6f85b2e4-9a7c-4758-a14a-8e243e3abbed/**
